import Header from "./components/Header";
import Wrapper from "./components/Wrapper";
import "./globals.css";
import { Sora } from "next/font/google";

const inter = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Header />
          <main className="px-20">{children}</main>
        </Wrapper>
      </body>
    </html>
  );
}
